<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function pumpjack_helper_ctools_plugin_api($module, $api) {
  if ($module == 'context' && $api == 'plugins') {
    return array('version' => 3);
  }
}

/**
 * Implements hook_context_plugins().
 */
function pumpjack_helper_context_plugins() {
  $plugins = array();

  /**
   * Reactions
   */
  $plugins['pumpjack_helper_addjs'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'pumpjack_helper') . '/plugins',
      'file' => 'pumpjack_helper_addjs.inc',
      'class' => 'pumpjack_helper_addjs',
      'parent' => 'context_reaction',
    ),
  );

  return $plugins;
}

/**
 * Implements hook_context_registry().
 */
function pumpjack_helper_context_registry() {
  $registry = array();

  $registry['reactions'] = array(
    'pumpjack_helper_addjs' => array(
      'title' => t('Pumpjack JS'),
      'description' => t('Add pumpjack action and plugin JS assets.'),
      'plugin' => 'pumpjack_helper_addjs',
      'path' => drupal_get_path('module', 'pumpjack_helper') . '/plugins',
      'file' => 'pumpjack_helper_addjs.inc',
    ),
  );

  return $registry;
}

/**
 * Implements hook_context_page_reaction().
 */
function pumpjack_helper_context_page_reaction() {
  if ($plugin = context_get_plugin('reaction', 'pumpjack_helper_addjs')) {
    $plugin->execute();
  }
}
